# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Python requirements
python:
  install:
    - requirements: 4788/src/docs/requirements.txt

sphinx:
  builder: html
  configuration: 4788/src/docs/conf.py